### ISSUE TITLE
Why Arrival Time takes more precedence than Priority ? 

### ISSUE THREAD

**Issue by hariprasadraja** [sanketmahore/JobSchedulingPOC#2]
https://github.com/sanketmahore/JobSchedulingPOC/blob/de635437ff81946f47028309ab5ad8990435da2a/JobScheduling/SortImpl.go#L26

**Comment by sanketmahore** [comment]
I have assumed a no preemption priority queue. So if a higher priority task arrives after lower priority one, the execution of lower priority task will be completed before executing the higher one. 
i.e a lower priority task will not be preempted in-between to execute a higher priority task.

**Comment by hariprasadraja** [comment]
**Agreed**

In you task, inputs are pre defined, if it is dynamic then  as you say it will work. Can you bring the inputs in the dynamic way ?
